### ISSUE TITLE
Inquiry about Data Preprocessing for RoadAnomaly and Fishyscapes LAF Datasets

### ISSUE THREAD

**Issue by xiaoran-roosevelt** [vojirt/DaCUP#1]
Hello,

I am currently investigating the RoadAnomaly and Fishyscapes LAF datasets and would like to understand the data preprocessing steps involved. Since these datasets do not contain ground truth semantic segmentation maps, it's unclear how regions corresponding to roads are identified. I could not find details on the preprocessing methods in either the associated papers or the code.

Could you please provide some insights into how the data is prepared and processed for evaluation? I look forward to your response.

Thank you!

**Comment by vojirt** [comment]
Hi, both of these datasets have annotation available for road, anomaly and ignore regions. This is sufficient for evaluation of the anomaly detection methods. These datasets are not used for training, thus full semantic annotation is not required nor provided as far as I know. For further questions and details, I would suggest to contact the authors of the respective datasets.

**Comment by xiaoran-roosevelt** [comment]
> Hi, both of these datasets have annotation available for road, anomaly and ignore regions. This is sufficient for evaluation of the anomaly detection methods. These datasets are not used for training, thus full semantic annotation is not required nor provided as far as I know. For further questions and details, I would suggest to contact the authors of the respective datasets.
Here is the translation:

But the annotation files of these datasets only contain three values: 0 for normal pixels, 1 for anomalous pixels, and 255 for ignored regions. However, the normal region includes both road and non-road areas, so how do we differentiate between roads and non-roads?
