### ISSUE TITLE
Inquiry about Data Preprocessing for RoadAnomaly and Fishyscapes LAF Datasets

### ISSUE THREAD

**Issue by xiaoran-roosevelt** [vojirt/DaCUP#2]
Hi, both of these datasets have annotation available for road, anomaly and ignore regions. This is sufficient for evaluation of the anomaly detection methods. These datasets are not used for training, thus full semantic annotation is not required nor provided as far as I know. For further questions and details, I would suggest to contact the authors of the respective datasets.

_Originally posted by @vojirt in https://github.com/vojirt/DaCUP/issues/1#issuecomment-2082541755_

**Comment by xiaoran-roosevelt** [comment]
But the annotation files of these datasets only contain three values: 0 for normal pixels, 1 for anomalous pixels, and 255 for ignored regions. However, the normal region includes both road and non-road areas, so how do we differentiate between roads and non-roads?

**Comment by xiaoran-roosevelt** [comment]
> ```
>           Hi, both of these datasets have annotation available for road, anomaly and ignore regions. This is sufficient for evaluation of the anomaly detection methods. These datasets are not used for training, thus full semantic annotation is not required nor provided as far as I know. For further questions and details, I would suggest to contact the authors of the respective datasets.
> ```
> 
> _Originally posted by @vojirt in [#1 (comment)](https://github.com/vojirt/DaCUP/issues/1#issuecomment-2082541755)_
But the annotation files of these datasets only contain three values: 0 for normal pixels, 1 for anomalous pixels, and 255 for ignored regions. However, the normal region includes both road and non-road areas, so how do we differentiate between roads and non-roads?

**Comment by xiaoran-roosevelt** [comment]
![labels_semantic_color](https://github.com/vojirt/DaCUP/assets/48651387/670b6a10-d23b-4947-8fbc-01594d80bf35)
![15_Rechbergstr_Deckenpfronn_000004_000270_gtCoarse_color](https://github.com/vojirt/DaCUP/assets/48651387/66048ac9-6997-49b8-9517-43f856217914)
This is an anomaly ground truth image from the Road Anomaly dataset, which only annotates anomalous and non-anomalous pixels without distinguishing between road and non-road areas. On the other hand, another image from the Lost and Found dataset annotates roads and anomalies on the roads. Therefore, I would like to know how your paper calculates anomalies only on the road for the Road Anomaly dataset.

**Comment by vojirt** [comment]
Now I understand your question. I have annotated manually the road region (in the same coarse fashion as in the FS LaF dataset) for the RoadAnomaly datasets and merged it with the original annotation such that I have 3 labels (road, non-road, anomaly). Here is the link to the annotation: https://drive.google.com/file/d/1SaRT_c-AfCzEBUBXZrKBccHwz5Wl6W94/view?usp=sharing

Cheers!

**Comment by xiaoran-roosevelt** [comment]
Thanks
